apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  description: "Authentication and Authorization service"
  annotations:
    # CRÍTICO: slug correto para habilitar a aba de Logs e Métricas que criamos
    github.com/project-slug: TalesBusiness/auth-service
    # Habilita a documentação via TechDocs
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - security
    - auth
spec:
  type: service
  lifecycle: production
  owner: team-devops
  system: security-system
  
  # API que este serviço disponibiliza para outros
  providesApis:
    - auth-api

  # Mapeamento de Dependências (Grafo de Relações)
  dependsOn:
    - resource:default/auth-db
    - component:default/api-gateway

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Interface OpenAPI para o serviço de autenticação
  annotations:
    # Permite que o Swagger UI renderize a documentação da API
    backstage.io/view-url: https://github.com/TalesBusiness/auth-service/blob/main/openapi.yaml
spec:
  type: openapi
  lifecycle: production
  owner: team-devops
  definition:
    # O Backstage lerá o conteúdo do arquivo YAML diretamente do GitHub
    $text: https://github.com/TalesBusiness/auth-service/blob/main/openapi.yaml
