apiVersion: backstage.io/v1alpha1 # Atualizado para v1alpha1 (padrão estável para Component)
kind: Component
metadata:
  name: auth-service
  description: Authentication service
  tags:
    - authentication
    - security
    - javascript
  links:
    - url: https://google.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
spec:
  type: service
  lifecycle: production
  owner: team-devops
  providesApis:
    - auth-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: API description of the auth-api interface
spec:
  type: openapi
  lifecycle: production
  owner: team-devops
  apiProvidedBy:
    - component:auth-service