apiVersion: backstage.io/v1beta1
kind: Component
metadata:
    name: auth-service
    description: Authentication service
    tags:
        - authentication
        - security
        - javascript
    links:
        - url: https://google.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
spec:
    type: service
    lifecycle: production
    owner: group:default/team-name