apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: auth-service
  description: "Authentication and Authorization service"
  annotations:
    # Vincula o serviço ao repositório para métricas e logs funcionarem
    github.com/project-slug: TalesBusiness/auth-service 
    backstage.io/techdocs-ref: dir:.
  tags:
    - python
    - security
    - auth
spec:
  type: service
  lifecycle: production
  owner: team-devops
  system: security-system # Agrupa serviços relacionados
  providesApis:
    - auth-api
  # Exemplo de mapeamento de dependências
  dependsOn:
    - resource:default/auth-db # Depende de um banco
    - component:default/api-gateway # Depende do gateway
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: auth-api
  description: Interface OpenAPI para o serviço de autenticação
spec:
  type: openapi
  lifecycle: production
  owner: team-devops
  definition:
    $text: https://github.com/TalesBusiness/auth-service/blob/main/openapi.yaml
