apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopping-cart
spec:
  dependsOn:
    - component:inventory
  type: website
  lifecycle: production
  owner: user:tales-andre
  system: purchasing
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory
spec:
  type: service
  lifecycle: production
  owner: ecommerce
  system: purchasing
---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: purchasing
  description: Description of system-name
spec:
  owner: group:ecommerce
  Domains: shopping-app

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shopping-app
  description: Everything about domain-name
spec:
  owner: group:ecommerce