apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: shopping-cart
spec:
  dependsOn:
    - component:inventory
  type: website
  lifecycle: production
  owner: user:tales-andre
  system: purchasing
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory
spec:
  dependsOn:
    - resource:inventory-db
  type: service
  lifecycle: production
  owner: ecommerce
  system: purchasing
---

apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: purchasing
  description: Description of system-name
spec:
  owner: group:ecommerce
  domain: shopping-app
---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: shopping-app
  description: Everything about domain-name
spec:
  owner: group:ecommerce
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: inventory-db  
  description: Description of resource-name
spec:
  type: database
  owner: group:ecommerce
  system: purchasing