apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-devops
  description: Time de Engenharia de Plataforma e Cloud
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: talescv
spec:
  memberOf: [team-devops]