apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: s3-bucket-pessoal-aprovacao
  title: "AWS S3 com PR e Aprovação"
  description: "Cria um PR para infraestrutura S3."
  tags:
    - aws
    - s3
  annotations:
    github.com/project-slug: tales-andre/templates-backstage
spec:
  owner: team-devops
  type: service

  parameters:
    - title: "Configurações do Bucket"
      required: [name, owner_team]
      properties:
        name:
          title: "Nome do Bucket S3"
          type: string
          description: "Nome único do bucket (ex: meu-bucket-logs)" # ✅ Aspas adicionadas aqui
          ui:autofocus: true
        
        owner_team:
          title: "Time Responsável"
          type: string
          description: "Quem será o dono deste recurso?"
          enum:
            - team-devops
            - team-engenharia
            - team-gerencia
          default: team-devops

  steps:
    - id: fetch-base
      name: Gerar Arquivos Terraform
      action: fetch:template
      input:
        url: ./content 
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner_team }}

    - id: log-policy
      name: Validando Políticas
      action: debug:log
      input:
        message: "Aplicando tags para ${{ parameters.owner_team }}"

    - id: publish-pr
      name: Criar Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=infra-pessoal&owner=tales-andre
        branchName: feature/s3-${{ parameters.name }}
        title: "Infra: Criação do Bucket ${{ parameters.name }}"
        description: |
          # Solicitação de Novo Bucket S3
          **Recurso:** ${{ parameters.name }}
          **Solicitante:** ${{ user.ref }}
        
    # Se quiser registrar automaticamente depois do merge, descomente abaixo:
    # - id: register
    #   name: Registrar no Backstage
    #   action: catalog:register
    #   input:
    #     repoContentsUrl: ${{ steps['publish-pr'].output.remoteUrl }}
    #     catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
      - title: "🚀 Acessar Pull Request"
        url: ${{ steps['publish-pr'].output.remoteUrl }}
      - title: "📂 Ver Repositório"
        url: https://github.com/tales-andre/infra-pessoal
