apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sqs-sns-pessoal-aprovacao
  title: "AWS SQS+SNS com PR e Aprovação"
  description: "Cria um PR para infraestrutura Pub/Sub (SQS/SNS)."
  tags:
    - aws
    - sqs
    - sns
  annotations:
    github.com/project-slug: TalesBusiness/infra-pessoal
spec:
  owner: team-devops
  type: service

  parameters:
    - title: "Configurações do Recurso"
      required: [component_id, region]
      properties:
        component_id:
          title: "Nome do Recurso"
          type: string
          description: "Nome base para a Fila e o Tópico (ex: pagamentos-events)"
          ui:autofocus: true
        
        region:
          title: "Região AWS"
          type: string
          description: "Região onde o recurso será criado"
          enum:
            - us-east-1
            - sa-east-1
          default: us-east-1

  steps:
    - id: fetch-base
      name: Gerar Arquivos Terraform
      action: fetch:template
      input:
        # ⚠️ SE O TEMPLATE ESTÁ DENTRO DA PASTA JUNTO COM O MAIN.TF, USE "./"
        # SE O TEMPLATE ESTÁ NA RAIZ, USE "./skeleton-sqs-sns"
        url: ./skeleton-sqs-sns 
        
        # ✅ ADICIONE ISSO: Cria uma pasta separada para não misturar arquivos
        targetPath: ./infra/sqs-${{ parameters.component_id }}
        
        values:
          component_id: ${{ parameters.component_id }}
          region: ${{ parameters.region }}

    - id: log-policy
      name: Validando Parâmetros
      action: debug:log
      input:
        message: "Iniciando provisionamento de ${{ parameters.component_id }} em ${{ parameters.region }}"

    - id: publish-pr
      name: Criar Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=infra-pessoal&owner=TalesBusiness
        branchName: feature/sqs-${{ parameters.component_id }}
        title: "Infra: Criação SQS/SNS ${{ parameters.component_id }}"
        description: |
          # Solicitação de Provisionamento Pub/Sub
          
          **Recurso:** ${{ parameters.component_id }}
          **Região:** ${{ parameters.region }}
          
          **Solicitante:** @${{ user.entity.metadata.name }}

  output:
    links:
      - title: "🚀 Acessar Pull Request"
        url: ${{ steps['publish-pr'].output.remoteUrl }}
      - title: "📂 Ver Repositório"
        url: https://github.com/TalesBusiness/infra-pessoal
