apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-sqs-sns
  title: Criar Fila SQS + Tópico SNS
  description: Provisiona um padrão Pub/Sub na AWS com SQS subscrito no SNS.
spec:
  owner: user:default/tales-andre
  type: service

  parameters:
    - title: Configuração do Recurso
      required:
        - component_id
        - region
      properties:
        component_id:
          title: Nome do Recurso
          type: string
          # 👇 CORREÇÃO: Aspas duplas adicionadas por causa do ":" dentro do texto
          description: "Nome base para a Fila e o Tópico (ex: pagamentos-events)"
          ui:autofocus: true
        region:
          title: Região AWS
          type: string
          default: us-east-1
          enum:
            - us-east-1
            - sa-east-1

  steps:
    - id: fetch-base
      name: Buscando Skeleton
      action: fetch:template
      input:
        url: ./skeleton-sqs-sns
        values:
          component_id: ${{ parameters.component_id }}
          region: ${{ parameters.region }}

    - id: publish-pr
      name: Abrir Pull Request de Infra
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=infra-pessoal&owner=TalesBusiness
        branchName: feature/sqs-${{ parameters.component_id }}
        title: "Infra: Criação SQS/SNS ${{ parameters.component_id }}"
        description: |
          # Solicitação de Provisionamento Pub/Sub
          
          **Recurso:** ${{ parameters.component_id }}
          **Região:** ${{ parameters.region }}
          
          **Solicitante:** ${{ user.entity }}
        labels:
          - backstage
          - terraform
          - aws
